### ISSUE TITLE
Ganzones don't work after version R19

### ISSUE THREAD

**Issue by ukenjutsu** [IllidanS4/YSF#114] opened 2020-06-05 08:54 UTC
I waited one year. 
I thought this was an obvious bug and it would be fixed soon, but that didn't happen :(

**Comment by IllidanS4** [comment] 2020-06-05 11:14
I was not aware of this issue, since I usually have `UsePerPlayerGangZones 0`. But there's nothing extra that YSF does, you can simulate it pretty easily by yourself with a position check.

**Comment by n0bodysec** [comment] 2020-06-11 06:45
I think I've fixed this issue. See [this](https://gitlab.com/open-sas/ysf/-/commit/f5b8fff563c10679d1d51acc9491705727b5ce08).

Actually it was caused by byteClientSideZoneIDUsed array. The default value should be 0xFF, but currently is zero. Zero means that the gangzone is global and not per player (see [this](https://github.com/IllidanS4/YSF/blob/master/src/CPlayerData.cpp#L364)).

I don't think that it's the best way to fix the issue (the fix is a paste of older YSF versions). Maybe std::fill() would be better, or use another values to check if the gangzone is global or per player.

I assume that it was the issue since I've never used these functions before.

**Comment by ukenjutsu** [comment] 2020-06-16 10:15
I don't know much English, so it’s easier for me to record a [video](https://youtu.be/W-86cDgw0u8)

**Comment by n0bodysec** [comment] 2020-06-16 17:44
Are you using the latest binaries from AppVeyor?
https://ci.appveyor.com/project/n0bodysec/ysf/build/job/xn004j86eqfv10vh/artifacts

**Comment by ukenjutsu** [comment] 2020-06-17 10:54
> Are you using the latest binaries from AppVeyor?
> https://ci.appveyor.com/project/n0bodysec/ysf/build/job/xn004j86eqfv10vh/artifacts

I used original YSF 2.0

UPDATED:
With your version everything working fine.
Thank you.

**Comment by ukenjutsu** [comment] 2020-06-17 11:00
`native GetPlayerWorldBounds(playerid, &Float:x_max, &Float:x_min = 0.0, &Float:y_max = 0.0, &Float:y_min = 0.0);`

error 025: function heading differs from prototype

A small bug, but i already tired of fixing it in the include
It shoud be like this &Float:x_xxx = 0.0, but it works only like this &Float:x_xxx

**Comment by IllidanS4** [comment] 2020-06-17 12:46
No idea how you get these issues. TogglePlayerGhostMode works in YSF 2.0 and there are no issues with the include file (assuming you are using the latest-ish version of the compiler).

**Comment by ukenjutsu** [comment] 2020-06-17 13:49
> No idea how you get these issues. TogglePlayerGhostMode works in YSF 2.0 and there are no issues with the include file (assuming you are using the latest-ish version of the compiler).

I used pawn compiler 3.10.9, now updated to 3.10.10 ([zeex release](https://github.com/pawn-lang/compiler/releases/tag/v3.10.10))
Еhis didn't help to fix the error

**Comment by n0bodysec** [comment] 2020-06-17 16:17
> 
> 
> `native GetPlayerWorldBounds(playerid, &Float:x_max, &Float:x_min = 0.0, &Float:y_max = 0.0, &Float:y_min = 0.0);`
> 
> error 025: function heading differs from prototype

I'm sure you are using fixes.inc.
Put this on your gamemode:
`#define FIX_GetPlayerWorldBounds 0`



> 
> 
> As I understand it, TogglePlayerGhostMode stops syncing the player for all other players?

No, it toggles the ghost mode function (players can walk through you).

**Comment by ukenjutsu** [comment] 2020-06-18 08:02
> > `native GetPlayerWorldBounds(playerid, &Float:x_max, &Float:x_min = 0.0, &Float:y_max = 0.0, &Float:y_min = 0.0);`
> > error 025: function heading differs from prototype
> 
> I'm sure you are using fixes.inc.
> Put this on your gamemode:
> `#define FIX_GetPlayerWorldBounds 0`
> 
> > As I understand it, TogglePlayerGhostMode stops syncing the player for all other players?
> 
> No, it toggles the ghost mode function (players can walk through you).
Yes, the bug was due to fixes.inc. Thank you

TogglePlayerGhostMode works fine, sorry for this

**Comment by n0bodysec** [comment] 2020-06-19 04:14
I'm glad to hear that :)

**Comment by IllidanS4** [comment] 2020-06-20 17:45
Fixed in b725a431f33e60387d657638b5247b765dff1023.

**Closed by IllidanS4** 2020-06-20 17:45 UTC
